README.md

READMEに環境構築手順を追記しました。

---

README.md

READMEに環境構築手順を追加

---

portal/src/main/resources/application.properties
portal/src/main/resources/static/css/home.css
portal/src/main/resources/templates/z/userDetail.html

#34 ユーザー詳細画面の更新と削除ボタンの配置を変えたい

---

src/main/resources/templates/z/login.html

Issues #24　対応。

---

src/main/resources/static/css/home.css
src/main/resources/templates/z/footer.html
src/main/resources/templates/z/home.html
src/main/resources/templates/z/homeLayout.html
src/main/resources/templates/z/login.html
src/main/resources/templates/z/userDetail.html
src/main/resources/templates/z/userList.html
src/main/resources/templates/z/userUpdate.html

Issues #24　対応

---

src/main/java/com/portal/z/password_change/domain/service/Password_changeService.java
src/main/java/com/portal/z/user/controller/userController.java

一部、Ｓｅｒｖｉｃｅを呼ばないで直接repositoryを呼んでいた処理があったので、訂正。

Issues #81　対応

---

pom.xml
src/main/java/com/portal/z/common/aspect/LogAspct.java
src/main/java/com/portal/z/common/domain/util/Utility.java
src/main/java/com/portal/z/user/controller/userController.java
src/main/java/com/portal/z/user/domain/model/UserListXlsxView.java
src/main/resources/com/portal/z/common/domain/repository/EnvMapper.xml
src/main/resources/com/portal/z/common/domain/repository/RoleMapper.xml
src/main/resources/com/portal/z/common/domain/repository/UserMapper.xml
src/main/resources/templates/z/userList.html

何とか出来ましたが、こんな感じで良いのかな？？ 😺 
あと、日付変換のあたりを、もう少し共通化したい。
⇒いろいろ格闘してしまったので、少し散らかっていますが、中心は「UserListXlsxView.java」ですので、そこだけでも見て欲しいな。 🙏

Issues #16　対応

---

src/main/java/com/portal/z/user/domain/model/InputForm.java

#62 の対応です。#73ブランチにプルリクエストしました。
ログイン失敗回数に上限を設定することでDBエラーの発生を防ぎます。
方法：
・InputFormクラスに@Maxを追加しました
・値は10です
・グループはUpdateOrderを使用します

#62 ログイン失敗回数に上限を設定しました

---

src/main/java/com/portal/z/common/domain/util/Utility.java
src/main/java/com/portal/z/user/controller/userController.java
src/main/resources/messages.properties
環境構築補足.md

暫定でユーザーIDの項目エラーとして扱ってます。
システムエラーとしたほうがよければ対応するので教えて下さいm(_ _)m

#13 の対応をしました。とりあえず #8 のほうにプルリクエストおくります。

---

src/main/java/com/portal/z/home/controller/HomeController.java
src/main/resources/templates/z/general.html
src/main/resources/templates/z/homeLayout.html

Issues #118　対応

---

src/main/java/com/portal/z/common/domain/service/RegistuserService.java
src/main/java/com/portal/z/common/domain/service/UserDetailsServiceImpl.java
src/main/java/com/portal/z/common/domain/util/Utility.java
src/main/java/com/portal/z/user/controller/userController.java

202011 #84

---

src/test/java/com/portal/z/common/domain/util/UtilityTest.java
環境構築補足.md

まずは簡単なテストを作成しました。ご確認ください。
環境変数を@TestPropertySourceで設定するようにしています。
環境変数(実行の構成で設定しているDATASOURCE_URLなど)を変更している場合は修正が必要です。
@suzuki-takashi 
今回テスト対象のメソッドはDBアクセスをしていませんが、Spring Boot は起動時にDBアクセスの設定をチェックしてしまうので、クラスのアノテーションで設定しています。

[FIX] #112 テストクラスの作成をしました。

---

src/main/resources/templates/z/userDetail.html
src/main/resources/templates/z/userList.html
src/main/resources/templates/z/userUpdate.html

#52　対応プルリクエストです。
やり方と内容あっていますでしょうか？
確認お願いいたします。

issue #52 ボタン文字指定の変更　対応

---

src/main/java/com/portal/z/common/controller/GlobalControllAdvice.java
src/main/java/com/portal/z/common/domain/service/RegistuserService.java
src/main/java/com/portal/z/common/exception/ApplicationException.java
src/main/java/com/portal/z/common/exception/Errors.java
src/main/java/com/portal/z/common/exception/HttpErrors.java
src/main/java/com/portal/z/user/controller/userController.java

１．package com.portal.z.common.exceptionにビジネス例外を追加しました。
　　　⇒ここに「①アプリケーション例外を実装する」を実装しました。
　　　　だだし、https://www.slideshare.net/shintanimoto/spring-boot10のＰ７４については行っていません。
２．RegistuserServiceの中で一意制約エラーを拾ってビジネス例外としています。
　　　⇒ここに「②一意制約違反の場合、①のアプリケーション例外を投げるようにする」を実装しました。
３．userControllerでビジネス例外を拾いました。

Issue #94　対応

---

src/main/java/com/portal/z/user/controller/userController.java

Issue #67　対応

---

src/main/java/com/portal/z/common/config/AuthenticationSuccessEventListener.java
src/main/java/com/portal/z/common/domain/repository/UserMapper.java
src/main/java/com/portal/z/common/domain/service/UserService.java
src/main/resources/com/portal/z/common/domain/repository/UserMapper.xml

mybatisで実装してます。
JdbcTemplateに書き直したほうがよかったら教えてください

#75の対応　ログイン成功時にログイン失敗回数を0回にするように変更しました。

---

src/main/java/com/portal/z/common/config/AuthenticationSuccessEventListener.java
src/main/java/com/portal/z/common/config/BadCredentialsEventListener.java
src/main/resources/com/portal/z/common/domain/repository/UserMapper.xml

Issue #166　対応

---

src/main/java/com/portal/z/common/domain/util/Constants.java

Issue #172　対応

---

src/main/java/com/portal/z/contact/controller/ContactController.java
src/main/resources/templates/z/contact.html

・問い合わせ画面のユーザIDとメールアドレスを初期表示し、読み取り専用
・問い合わせ画面の結果表示場所を上に。（スマホ用）

Issue #172 対応

---

environment/01_DATABASE/CREATEDATABASE.sql

Issue #35 対応

---

src/main/java/com/portal/z/user/controller/userController.java
src/main/resources/templates/z/userUpdate.html

bindingResultにエラーの結果をセットするようにしていましたが、返ってくるのは業務エラーなので、modelにセットして画面上部に表示する方式の方が他の画面との整合もとれて良いと思います。

Issue #93 対応

---

environment/01_DATABASE/CREATEDATABASE.sql
environment/02_TABLE/ZM001_USER(ユーザマスタ).sql
environment/02_TABLE/ZM002_ROLE(ロールマスタ).sql
environment/02_TABLE/ZM003_USERROLE(ユーザロールマスタ).sql
environment/02_TABLE/ZM004_EMP(従業員マスタ).sql
environment/02_TABLE/ZM500_ROLE_NAME_LIST(ロール名).sql
environment/02_TABLE/ZM999_ENV(環境マスタ).sql
environment/02_TABLE/ZT001_PWREISSUEINFO(パスワード再発行情報).sql

issue #197　対応

---

src/main/java/com/portal/z/env/domain/model/InputEnvForm.java
src/main/resources/messages.properties
src/main/resources/templates/z/envDetail.html
src/main/resources/templates/z/envUpdate.html

Issue #177 対応

---

src/main/resources/templates/z/envDetail.html
src/main/resources/templates/z/envList.html
src/main/resources/templates/z/userDetail.html
src/main/resources/templates/z/userList.html

Issue #177　対応

---

src/main/java/com/portal/z/env/domain/model/InputEnvForm.java
src/main/resources/static/css/home.css
src/main/resources/templates/z/contact.html
src/main/resources/templates/z/envDetail.html
src/main/resources/templates/z/envList.html
src/main/resources/templates/z/envUpdate.html
src/main/resources/templates/z/footer.html
src/main/resources/templates/z/home.html
src/main/resources/templates/z/homeLayout.html
src/main/resources/templates/z/login.html
src/main/resources/templates/z/pwreissue.html
src/main/resources/templates/z/resetpassword.html
src/main/resources/templates/z/userDetail.html
src/main/resources/templates/z/userList.html
src/main/resources/templates/z/userUpdate.html

issue #166 対応

---

src/main/java/com/portal/z/common/domain/model/Env.java
src/main/java/com/portal/z/common/domain/model/Pwreissueinfo.java
src/main/java/com/portal/z/common/domain/model/Role.java
src/main/java/com/portal/z/common/domain/model/User.java
src/main/java/com/portal/z/common/domain/service/UserSharedServiceImpl.java
src/main/java/com/portal/z/common/domain/util/DateUtils.java
src/main/java/com/portal/z/pwreissue/domain/service/PwreissueServiceImpl.java
src/main/java/com/portal/z/resetpassword/controller/ResetpasswordController.java
src/main/java/com/portal/z/user/controller/userController.java
src/main/java/com/portal/z/user/domain/model/InputForm.java
src/main/java/com/portal/z/user/domain/model/SelectForm.java
src/main/resources/messages.properties
src/main/resources/templates/z/password_change.html
src/test/java/com/portal/z/common/domain/util/DateUtilsTest.java

Issue #223 対応

---

src/main/java/com/portal/z/password_change/domain/model/PasswordForm.java
src/main/java/com/portal/z/resetpassword/domain/model/ResetpasswordForm.java

パスワードの項目をもつフォームにアノテーションでチェックを追加
@suzuki-takashi 
すでに作業済みでしたら無視してくださいm(_ _)m

#243 passwordのチェックの展開

---

src/main/java/com/portal/z/common/domain/util/Constants.java
src/main/java/com/portal/z/common/domain/util/DateUtils.java
src/main/java/com/portal/z/user/controller/userController.java
src/test/java/com/portal/z/common/domain/util/DateUtilsTest.java

Issue #291 対応

---

src/main/java/com/portal/a/common/domain/model/Company.java
src/main/java/com/portal/a/common/domain/repository/CompanyMapper.java
src/main/java/com/portal/a/company/controller/companyController.java
src/main/java/com/portal/a/company/domain/model/InputCompanyForm.java
src/main/java/com/portal/a/company/domain/model/SelectCompanyForm.java
src/main/java/com/portal/a/company/domain/service/CompanyService.java
src/main/java/com/portal/a/company/domain/service/CompanyServiceImpl.java
src/main/resources/com/portal/a/common/domain/repository/CompanyMapper.xml
src/main/resources/com/portal/a/common/domain/repository/EnvMapper.xml
src/main/resources/messages.properties
src/main/resources/templates/a/companyDetail.html
src/main/resources/templates/a/companyList.html
src/main/resources/templates/a/companyUpdate.html
src/main/resources/templates/z/homeLayout.html

202106 #268

---

src/main/java/com/portal/a/employee/domain/model/CreateOrder.java
src/main/java/com/portal/a/employee/domain/model/UpdateOrder.java

[add] #272対応　社員マスタ画面追加

---

src/main/resources/templates/a/companyUpdate.html

会社マスタ新規追加時に会社CDと会社名にautofocusがついていたので、会社CDのみに変更。

[fix] #166対応　会社マスタ新規追加時の軽微な修正

---

src/main/resources/templates/a/empDetail.html

[fix] #272対応　社員マスタ画面の微回収

---

environment/03_DATA/bt001_skill.txt
src/main/resources/templates/a/empList.html

・社員マスタの検索ボタンの位置を修正
・スキル情報のテストデータ間違い修正

[fix] #166対応　社員マスタ検索ボタン移動

---

src/main/java/com/portal/a/company/controller/companyController.java
src/main/java/com/portal/a/company/domain/model/CompanyListCsvView.java
src/main/java/com/portal/a/company/domain/model/CompanyListXlsxView.java
src/main/resources/templates/a/companyList.html

202109 #343

---

src/main/java/com/portal/b/common/domain/repository/CareertechnologyMapper.java

[add] #308対応　業務経歴詳細画面修正

---

src/main/resources/static/js/weather.js
src/main/resources/templates/z/home.html
src/main/resources/templates/z/homeLayout.html

[update] #166対応　トップ画面の天気予報あたりを整理

---

src/main/resources/templates/z/home.html
src/main/resources/templates/z/homeLayout.html

[update] #166対応　TOPメニューを整理

---

src/main/resources/templates/a/empPerson.html

[update] #166対応　業務経歴書ボタン表示変更

---

src/main/java/com/portal/b/skill/domain/model/SkillReportXlsxView.java

[fix] #166対応　業務経歴書の備考の位置を微調整

---

src/main/resources/templates/b/skillDetail.html

[update] #166対応　スキル情報詳細のレイアウトを微調整

---

src/main/resources/templates/b/careerDetail.html
src/main/resources/templates/b/careerUpdate.html
src/main/resources/templates/b/skillDetail.html

[update] #166対応　スキル情報詳細のレイアウトを微調整1

---

src/main/resources/templates/b/careerDetail.html
src/main/resources/templates/b/careerUpdate.html
src/main/resources/templates/b/skillDetail.html

[update] #166対応　スキル情報詳細のレイアウトを微調整2

---

src/main/resources/templates/b/careerDetail.html
src/main/resources/templates/b/careerUpdate.html
src/main/resources/templates/b/skillDetail.html

[update] #166対応　スキル情報詳細のレイアウトを微調整3

---

src/main/resources/templates/b/careerDetail.html
src/main/resources/templates/b/careerUpdate.html
src/main/resources/templates/b/skillDetail.html

[update] #166対応　スキル情報詳細のレイアウトを微調整4

---

src/main/resources/templates/b/careerDetail.html

[update] #166対応　スキル情報詳細のレイアウトを微調整5

---

src/main/resources/templates/a/empPerson.html
src/main/resources/templates/b/careerDetail.html

[update] #166対応　スキル情報詳細のレイアウトを微調整6

---

src/main/resources/templates/b/careerDetail.html

[update] #166対応　スキル情報詳細のレイアウトを微調整7

---

src/main/resources/templates/b/careerDetail.html

[update] #166対応　スキル情報詳細のレイアウトを微調整8

---

src/main/resources/templates/b/careerDetail.html

[update] #166対応　スキル情報詳細のレイアウトを微調整9

---

src/main/resources/templates/b/careerDetail.html

[update] #166対応　スキル情報詳細のレイアウトを微調整12

---

src/main/resources/templates/b/careerDetail.html

[update] #166対応　スキル情報詳細のレイアウトを微調整13

---

src/main/resources/templates/a/positionList.html
src/main/resources/templates/a/positionUpdate.html
src/main/resources/templates/b/careerDetail.html
src/main/resources/templates/b/careerUpdate.html
src/main/resources/templates/b/skillDetail.html
src/main/resources/templates/z/userDetail.html

[update] #166対応　inputmodeの設定

---

src/main/resources/messages.properties

[update] #425対応　メッセージ微調整

---

src/main/java/com/portal/a/employee/controller/empController.java
src/main/java/com/portal/z/common/domain/util/StrUtils.java
src/test/java/com/portal/z/common/domain/util/StrUtilsTest.java

[fix] #166対応　郵便番号を未入力で登録するとエラーが出るinputmodeの設定

---

src/main/resources/static/js/portal.js
src/main/resources/templates/a/empDetail.html
src/main/resources/templates/a/empUpdate.html

[fix] #166対応　最寄り駅CDの入力を非表示に変更

---

src/main/resources/templates/a/companyDetail.html
src/main/resources/templates/a/companyUpdate.html
src/main/resources/templates/a/empDetail.html
src/main/resources/templates/a/empPerson.html
src/main/resources/templates/a/empUpdate.html
src/main/resources/templates/a/envDetail.html
src/main/resources/templates/a/envUpdate.html
src/main/resources/templates/a/positionDetail.html
src/main/resources/templates/a/positionUpdate.html
src/main/resources/templates/b/careerDetail.html
src/main/resources/templates/b/careerUpdate.html
src/main/resources/templates/b/skillDetail.html
src/main/resources/templates/z/userDetail.html
src/main/resources/templates/z/userList.html
src/main/resources/templates/z/userUpdate.html

・各画目のブレークポイントが狭すぎるのでもう少し拡げました。

[fix] #166対応　各画面サイズを微調整

---

src/main/java/com/portal/a/employee/controller/empController.java
src/main/resources/templates/a/empDetail.html
src/main/resources/templates/a/empUpdate.html

・都道府県一覧をAPIから入手していたが、APIリクエスト回数制限にひっかかってしまうので、内部に持つことにしました。

[update] #166対応　都道府県選択を変更

---

src/main/java/com/portal/b/common/domain/repository/SkillMapper.java
src/main/java/com/portal/b/skill/controller/skillController.java
src/main/java/com/portal/b/skill/domain/model/SelectSkillForm.java
src/main/java/com/portal/b/skill/domain/service/SkillService.java
src/main/java/com/portal/b/skill/domain/service/SkillServiceImpl.java
src/main/resources/com/portal/b/common/domain/repository/SkillMapper.xml
src/main/resources/templates/b/skillList.html

[update] #166対応　スキル情報を組織名で検索可能にした

---

src/main/resources/templates/a/empDetail.html
src/main/resources/templates/a/empPerson.html
src/main/resources/templates/a/empUpdate.html
src/main/resources/templates/b/careerDetail.html
src/main/resources/templates/b/careerUpdate.html
src/main/resources/templates/b/skillDetail.html

[update] #166対応　画面レイアウトを微調整

---

src/main/resources/templates/z/userList.html

@suzuki-takashi  レビューありがとうございます。ご指摘のクリアボタンの位置を修正しましたので、確認をお願いします。

[UPDATE] #381 レビュー指摘修正：クリアボタンの位置修正

---

src/main/java/com/portal/a/common/domain/repository/OrganizationMapper.java
src/main/java/com/portal/a/organization/controller/organizationController.java
src/main/java/com/portal/a/organization/domain/model/CreateOrder.java
src/main/java/com/portal/a/organization/domain/model/InputOrganizationForm.java
src/main/java/com/portal/a/organization/domain/model/OrganizationListXlsxView.java
src/main/java/com/portal/a/organization/domain/model/SelectOrganizationForm.java
src/main/java/com/portal/a/organization/domain/model/UpdateOrder.java
src/main/java/com/portal/a/organization/domain/model/ValidCreate1.java
src/main/java/com/portal/a/organization/domain/model/ValidCreate2.java
src/main/java/com/portal/a/organization/domain/model/ValidUpdate1.java
src/main/java/com/portal/a/organization/domain/model/ValidUpdate2.java
src/main/java/com/portal/a/organization/domain/service/OrganizationService.java
src/main/java/com/portal/a/organization/domain/service/OrganizationServiceImpl.java
src/main/resources/com/portal/a/common/domain/repository/OrganizationMapper.xml
src/main/resources/messages.properties
src/main/resources/templates/a/organizationDetail.html
src/main/resources/templates/a/organizationList.html
src/main/resources/templates/a/organizationUpdate.html
src/main/resources/templates/z/homeLayout.html

202110 #269

---

src/main/java/com/portal/a/organization/controller/organizationController.java
src/main/java/com/portal/a/organization/domain/model/InputOrganizationForm.java
src/main/java/com/portal/a/organization/domain/model/OrganizationListXlsxView.java

[update] #166対応　共通処理差し替え

---

src/main/resources/templates/a/companyDetail.html
src/main/resources/templates/a/envDetail.html
src/main/resources/templates/a/positionDetail.html
src/main/resources/templates/z/userDetail.html

[update] #166対応　autofocus調整

---

src/main/resources/templates/a/empList.html

[update] #478対応　チェックボックスのラベルを調整
